services:
  - type: web
    name: mlpi
    env: python
    region: us
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
